---
title: ''
output:
github_document:
toc: yes
toc_float: yes
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
theme_set(theme_bw())
ggplot <- function(...) ggplot2::ggplot(...) + scale_fill_manual(values=cbbPalette) + scale_color_manual(values=cbbPalette)+theme(legend.position="bottom")

fig_path = '/Users/zeynepenkavi/Dropbox/PoldrackLab/DevStudy_Analyses/output/figures/'
```

```{r}
design = read.csv('~/Downloads/sub-400742_run-001_level1_design_matrix_centpo.csv')
names(design)
summary(scale(design$std_dvars, scale=F))
```


```{r message=FALSE}
design %>%
  mutate(std_dvars = scale(design$std_dvars, scale=F)[1:216],
         constant=0) %>%
  gather(reg, value, -X) %>%
  mutate(reg = gsub("derivative", "td", reg),
         reg = gsub("_", " ", reg),
         reg = gsub("framewise displacement", "FD", reg),
         reg = factor(reg, levels = c("m1", "m1 td","m2", "m2 td","m3", "m3 td", "m4", "m4 td", "m1 rt", "m1 rt td",  "m2 rt", "m2 rt td",  "m3 rt", "m3 rt td",  "m4 rt", "m4 rt td", "gain","gain td","loss", "loss td","junk", "junk td","rot x", "rot x td", "rot x sq", "rot x sq td", "rot y", "rot y td", "rot y sq", "rot y sq td", "rot z", "rot z td", "rot z sq", "rot z sq td", "trans x", "trans x td", "trans x sq", "trans x sq td", "trans y", "trans y td", "trans y sq", "trans y sq td", "trans z", "trans z td", "trans z sq", "trans z sq td", "FD", "std dvars", "scrub","drift 1", "drift 2", "constant"))) %>%
  ggplot(aes(y=X, x=factor(reg)))+
  geom_tile(aes(fill=value), color=NA)+
  scale_x_discrete(labels = function(x) str_wrap(x, width=15))+
  scale_fill_gradient(low="red", high="white")+
  xlab("")+
  ylab("")+
  theme(axis.text.y = element_blank(),
        legend.position = "none",
        axis.ticks = element_blank(),
        axis.text.x = element_text(angle=90, margin = margin(t=-18),hjust=0.95,vjust=0.2),
        panel.border = element_blank(),
        panel.grid = element_blank())

ggsave("Sample_design_matrix.jpeg", device = "jpeg", path = fig_path, width = 9, height = 5, units = "in", dpi = 450)
```