---
title: adolescent experiential learning  
author:
  - name: A. Zeynep Enkavi
    email: zenkavi@caltech.edu
    affiliation: California Institute of Technology
    footnote: 1
  - name: Russell A. Poldrack
    email: russpold@stanford.edu
    affiliation: Stanford University
address:
  - code: California Institute of Technology
    address: Division of Humanities and Social Sciences, 1200 E. California Blvd., Pasadena, CA, 91125
  - code: Stanford University
    address: Department of Psychology, 450 Jane Stanford Way, Stanford, CA, 94305
footnote:
  - code: 1
    text: "Corresponding Author"
abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "Neuroimage"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
#linenumbers: true
#numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
---

Introduction
=============

Learning from experience

Adolescent decision-making 
public health consequences
helps us understand the development of healthy and matured adult decision making.

benefited from developments in neuroimaging and a more formalized study of decision-making

developments in neuroimaging confirmed the importance of the prefrontal cortex, which was already known as the region that continued development at this stage



Computational models provide a quantitative way to relate the limited observable behavioral data to unobservable underlying cognitive processes and their biological correlates. They are used in two primary ways within cognitive neuroscience research. On the one hand, hypotheses on behavioral differences can be conceptualized as group differences in parameter estimates. In these studies the same model is fitted to each subject's data to estimate parameters. The subject-specific estimates are then compared between groups or related to another variable of interest. Alternatively, hypotheses on differing cognitive processes are resolved by comparing models. In these cases the hypotheses are specified in different models and multiple models are fit to each subject's data. Instead of subject-specific parameter estimates, descriptions of how well the models fit all the data are compared between models to determine the "winning model." In practice a comparison of parameter estimates between groups often follows a model comparison.

Particularly, prediction error models applied to experiential learning tasks present a rare success story in mapping behavior to a model parameter and then onto a neural correlate in the dopamine response.

In binary choice modeling there is also the caveat of mapping discrete outcomes to continuous values. This can be done either categorically with hardmax rules but much more frequently they are paarmeterized with a softmax choice rule.
The interpretation of the softmax temperature parameter presents a different challenge. From one perspective it represents how often the observed behavior can be explained by the latent variables in the computational models (in this case value differences) versus random choosing. If all of an observed behavioral difference between groups is attributed to a difference in this parameter it raises the question of whether the behavior is modeled correctly.

Methods
========

## Sample 

## Behavioral data

Outside the scanner

Inside the scanner

## Neuroimaging protocol

## Neuroimaging preprocessing

Results
========

## Behavioral results

## Neuroimaging results

Discussion
===========

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: One in text @Feynman1963118 and another at the sentence end [@Dirac1953888].

References {#references .unnumbered}
==========

